#
# Copyright (c) TcMenu organization.
# This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
#

name=Adafruit-GFX-mbed-fork
version=1.0.0
maintainer=https://tcmenu.github.io/documentation/
author=TcMenu
category=Other
url=https://github.com/TcMenu/Adafruit-GFX-mbed-fork
sentence=AdaFruit Fork for OLED using non arduino environment
paragraph=AdaFruit Fork for OLED using non arduino environment
includes=Adafruit_GFX.h
depends=IoAbstraction,tcUnicodeHelper
architectures=*
